
services:
  postgres-database:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: root     
      POSTGRES_PASSWORD: r123456
      POSTGRES_DB: nestjs     
    ports:
      - "5433:5432"               
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
  
volumes:
  postgres_data:

networks:
  my_network:
